### ISSUE TITLE
Управление заявками на регистрацию фонда в консоли администратора

### ISSUE THREAD

**Issue by zykindmitry** [zykindmitry/charityCRM#17]
В консоли администратора добавить поддержку следующих команд.

create-fund_regisration <наименование фонда> // создает заявку на регистрацию фонда
update-fund_registration <id> <наим. фонда> // исправляет наименование фонда в ранее созданной заявке
delete-fund_registration <id> // удаляет ранее созданную заявку
list-fund_registration [-all] // выводит все заявки на регистрацию фонда, если ключевое слово -all отсутствует, то выводятся только активные заявки

**Comment by nrdnfella** [comment]
Дмитрий, в конструкторе класса FundRegistration описан обязательный параметр maxLifeTime. По-умолчанию чему равен этот параметр? Или он будет задаваться в консоли администратора как параметр:  Напишите '{CommandText} [{NameParameter}] [{DescriptionParameter}] [{MaxLifeTime}]', чтобы создать заявку на регистрацию фонда?

**Comment by zykindmitry** [comment]
Этот параметр должен задаваться в конфигурационном файле appconfig.json ("FundRegistrationMaxLifeTime": "nn:nn:nn"). В рамках данной задачи можно просто захардкодить значение 24 часа.
